BINGX_API_KEY = 'XSYW1aZupheUL8hynSWqNEvCUkZ4OHkAvYVygQdxyMwNaYdjGz2hAOkG32qVghuw3vGO5JbdfxDKOIgSjwZA'
BINGX_SECRET_KEY = 'b4gc7Gibq2JwTGBGLghIRq2avGtxeTprwvg0Jbi9DmntFgE7r08MExZW6RKtohRelAwQL5jyEiGkIVQ7LtgGg'
LEVERAGE = 10
# TRADE_SIDE = {'LONG', 'SHORT'} #for v 0.0.3
TAKE_PROFIT = 10
INCREASE_FACTOR = 4
SYMBOL = 'DOGE/USDT:USDT'
