#Phantom API
BINGX_API_KEY = ''
BINGX_SECRET_KEY = ''
LEVERAGE = 10
# TRADE_SIDE = {'LONG', 'SHORT'} #for v 0.0.3
TAKE_PROFIT = 5
INCREASE_FACTOR = 4
SYMBOL = 'FET/USDT:USDT'
FIRST_POSITION_AMOUNT = 7
